### ISSUE TITLE
Choice: Designer or Developer?

### ISSUE THREAD

**Issue by riyadhalnur** [laurendorman/komputer-maschine#1]
It would be faster and more intuitive in some sense if the user was given the option of picking if they're a designer, developer or both. That way no one gets bloat installed, i.e I'm a developer and I don't need or want Sketch to be installed on my new machine, so I can opt-out of installing designer centric apps.

**Comment by laurendorman** [comment]
You pose a good question. How would you approach the segmentation here, @riyadhalnur?

**Comment by riyadhalnur** [comment]
From the list of what is being installed, I'd say

Developers' only apps -
1. Vagrant
2. VirtualBox
3. Docker
4. tmux
5. vim
6. zsh
7. iterm2

and vice versa

**Comment by laurendorman** [comment]
Ahh, yes. These could be categorized as "Developers' Essentials." However, many other tools listed are useful for Developers – which was the goal of the this repo. There are even a couple that are listed for fun, i.e. Spotify.

With that in mind, I would recommend anyone who clones the repo or downloads the script, go through the line items and remove the tools/applications they do not need.

I will add more details to the documentation surrounding this. Thank you for calling this out.
