### ISSUE TITLE
Failing after Google Chrome install

### ISSUE THREAD

**Issue by mkess-ivy** [laurendorman/komputer-maschine#3]
I already had Google Chrome installed, then ran the script.  It fails after it tries to install Chrome again.

**Comment by laurendorman** [comment]
@mkess-ivy, thanks for reporting! I will look into this.

**Comment by laurendorman** [comment]
@mkess-ivy, I recommend removing `google-chrome` from Line 130 in this case.

After some investigation, I've learned that Cask does not recognize applications that have been installed outside of Cask. 😢 

Alternatively, you could add `--force` to the end of Line 149 to force the installation of applications that have already been installed. From there, you could pop into your `~/Applications` folder and remove any duplicate applications if needed. 👍 

Thanks again for reporting. 😃
